name: Update GFW List Rules

on:
  schedule:
    - cron: '0 0 * * 0'  # 每周日午夜运行
  workflow_dispatch:  # 允许手动触发

jobs:
  update_gfwlist:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main
        token: ${{ secrets.TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run update_gfwlist.py
      run: python update_gfwlist.py

    - name: Add and commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add dns.rsc
        git commit -m "Update GFW list rules" || echo "No changes to commit"

    - name: Push changes
      run: git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
